config/routes.rb
MAFT::Application.routes.draw do

  root :to => 'home#index'
  match 'home', :to => 'home#index'
  match 'application/main_menu', :to => 'application#main_menu'
  match 'home/main_show', to: 'home#main_show'

  get "reporting/index", as: 'reports_index'

  post "reporting/get_report_data", to: "reporting#get_report_data", as: 'get_report_data'

  match 'project/add_users/:id/', :to => 'project#add_users#id', :via => :post
  match 'project/edit_team/:id', :to => 'project#edit_team#id'
  resources :project

  get "user/index(/:message)/", to: 'user#index#message',  as: 'users_index'
  get "user/change_roles/:id", to: 'user#change_roles#id',  as: 'user_change_role'
  post "user/update_roles/:id", to: 'user#update_roles#id',  as: 'user_roles'
  post "user/add_user_role", to: 'user#add_user_role'

  devise_for :users
  resources  :user

  match 'story_board/update_stages', to: 'story_board#update_stages'
  match 'story_board/reorder', to: 'story_board#reorder'
  match 'story_board/index/:id(/*other)', to: 'story_board#index#id'
  match 'story_board/get_project_tasks/:id', to: 'story_board#get_project_tasks#id'
  post 'story_board/get_form_objects', to: 'story_board#get_form_objects'
  resources :story_board

  get 'tdd/index', to: 'tdd#index', as: 'tdd_index'
  get 'tdd/view_tdd_process', to: 'tdd#view_tdd_process', as: 'view_tdd_process'
  get 'tdd/render_svg_image', to: 'tdd#render_svg_image'
  get 'tdd/vew_app_tests', to: 'tdd#vew_app_tests', as: 'vew_app_tests'
  get 'tdd/render_ruby_tests', to: 'tdd#render_ruby_tests', as: 'render_ruby_tests'
  get 'tdd/render_js_tests', to: 'tdd#render_js_tests', as: 'render_js_tests'

end

app/controllers/tdd_controller.rb
# @author jusef belkasemi
class TddController < ApplicationController
  skip_before_filter :authenticate_user!

  def index

  end

  def view_tdd_process

  end

  #this action will render the svg of the Solo TDD process diagram
  def render_svg_image
    response.headers['Content-Type'] = 'image/svg+xml'
    render :text => open('app/assets/images/tdd_process.svg').read
  end

  def vew_app_tests

  end

  def render_ruby_tests
    #response.headers['Content-Type'] = 'text/html'
    #render file: 'app/views/tdd/ruby_test', layout: false, format: 'html'
    render layout: false
  end

  def render_js_tests
    #response.headers['Content-Type'] = 'text/html'
    #render file: 'app/views/tdd/js_tests.html', layout: false, format: 'html'
    render layout: false
  end

end

app/helpers/tdd_helper.rb
module TddHelper
end

app/views/tdd/index.html.erb
<div class="page-content">
  <!--<ul class="large-block-grid-4 tdd-info-tiles">-->
    <!--<a href="javascript:void(0)">-->
    <!--<li class="">-->
      <!--<h5>MAFT Application Tests</h5>-->
      <!--<p>This section contains an interactive list of tests for MAFT web application. Both Rails and JS tests are available. Great place to look for code examples for your project</p>-->
    <!--</li></a>-->
    <!--<a href="<%= view_tdd_process_path %>">-->
      <!--<li class="">-->
      <!--<h5><i class="general foundicon-idea"></i> TDD Process for Solo Web Development</h5>-->
      <!--<p>This section contains an activity diagram giving guidance on how to follow the TDD process</p>-->
    <!--</li></a>-->
  <!--</ul>-->

  <ul class="small-block-grid-2 tdd-info-tiles">
    <li>
      <div class="panel">
        <h5><i class="general foundicon-tools"></i>&nbsp;MAFT Application Tests</h5>
      <p>This section contains an interactive list of tests for MAFT web application. Both Rails and JS tests are available. Great place to look for code examples for your project</p>
        <a href="<%= vew_app_tests_path %>" class="button success tiny radius">Go To Section</a>
      </div>
    </li>
    <li>
      <div class="panel">
      <h5><i class="general foundicon-idea"></i>&nbsp;TDD Process for Solo Web Development</h5>
      <p>This section contains an activity diagram giving guidance on how to follow the TDD process</p>
        <a href="<%= view_tdd_process_path %>" class="button success tiny radius">Go To Section</a>
      </div>
    </li>
  </ul>
</div>

app/views/tdd/vew_app_tests.html.erb
<div class="page-content">
  <div class="section-container vertical-tabs" data-section="vertical-tabs">
    <section>
      <p class="title" data-section-title><a href="javascript:void(0)" id="redner-ruby-tests">Ruby tests</a></p>
      <div class="content" data-section-content>
        <a href="https://bitbucket.org/jbelkasemi/maft/src/0533f37ae66ccc81566d62e4152c1cde3a0e674b/spec?at=master" target="_blank">View Ruby Test Source</a>
        <br />
        <iframe id="ruby-tests" src="<%= render_ruby_tests_path %>" data-url="<%= render_ruby_tests_path %>" width="100%" height="600px">
        </iframe>
      </div>
    </section>
    <section>
      <p class="title" data-section-title><a href="javascript:void(0)" id="redner-js-tests">JavaScript Tests</a></p>
      <div class="content" data-section-content>
        <a href="https://bitbucket.org/jbelkasemi/maft/src/0533f37ae66ccc81566d62e4152c1cde3a0e674b/spec/javascripts?at=master" target="_blank">View JavaScript Test Source</a>
        <br />
        <iframe id="js-tests" src="<%= render_js_tests_path %>" data-url="<%= render_js_tests_path %>" width="100%" height="600px">
        </iframe>
      </div>
    </section>
  </div>
</div>

app/views/tdd/view_tdd_process.html.erb
<div class="page-content">
  <div id="tdd-process-obj">
      <!--<object data="/tdd/render_svg_image" type="image/svg+xml"></object>-->
      <%= link_to(raw('<i class="general foundicon-left-arrow"></i>&nbsp;Return To TDD Info'), tdd_index_path, class: 'button secondary tiny round') %>
      <br/>
        <div>
      <embed src="/tdd/render_svg_image" type="image/svg+xml" width="100%"/>
        </div>
    </div>
</div>