config/routes.rb
MAFT::Application.routes.draw do

  root :to => 'home#index'
  match 'home', :to => 'home#index'
  match 'application/main_menu', :to => 'application#main_menu'
  match 'home/main_show', to: 'home#main_show'

  get "reporting/index", as: 'reports_index'

  post "reporting/get_report_data", to: "reporting#get_report_data", as: 'get_report_data'

  match 'project/add_users/:id/', :to => 'project#add_users#id', :via => :post
  match 'project/edit_team/:id', :to => 'project#edit_team#id'
  resources :project

  get "user/index(/:message)/", to: 'user#index#message',  as: 'users_index'
  get "user/change_roles/:id", to: 'user#change_roles#id',  as: 'user_change_role'
  post "user/update_roles/:id", to: 'user#update_roles#id',  as: 'user_roles'
  post "user/add_user_role", to: 'user#add_user_role'

  devise_for :users
  resources  :user

  match 'story_board/update_stages', to: 'story_board#update_stages'
  match 'story_board/reorder', to: 'story_board#reorder'
  match 'story_board/index/:id(/*other)', to: 'story_board#index#id'
  match 'story_board/get_project_tasks/:id', to: 'story_board#get_project_tasks#id'
  post 'story_board/get_form_objects', to: 'story_board#get_form_objects'
  resources :story_board

  get 'tdd/index', to: 'tdd#index', as: 'tdd_index'
  get 'tdd/view_tdd_process', to: 'tdd#view_tdd_process', as: 'view_tdd_process'
  get 'tdd/render_svg_image', to: 'tdd#render_svg_image'
  get 'tdd/vew_app_tests', to: 'tdd#vew_app_tests', as: 'vew_app_tests'
  get 'tdd/render_ruby_tests', to: 'tdd#render_ruby_tests', as: 'render_ruby_tests'
  get 'tdd/render_js_tests', to: 'tdd#render_js_tests', as: 'render_js_tests'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :remember_me, :name, :password_confirmation
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # To change this template use File | Settings | File Templates.
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :user_roles
end

app/controllers/user_controller.rb
# @author jusef belkasemi
class UserController < ApplicationController
  def index
    @message = params[:message]
    @current_user = User.find(current_user.id)
    @users = User.where("id <> '" + @current_user.id.to_s + "'").all
  end

  def add_user_role
    @message = ''
    @user = User.find(params[:id])
    @user_role = UserRole.find(params[:role_id])
    user_roles = @user.user_roles
    if (!user_roles.include?(@user_role))
      user_roles.create(@user_role)
      @message = @user_role.title + ' role has been added to ' + @user.name
    else
      @message = 'This role has already been added'
    end

    redirect_to action: 'index', :message => @message
  end

  def new
    @user = User.new
  end

  def create
    user = params[:user]
    password = generate_dummy_password
    user['password'] = password
    user['password_confirmation'] = password

    @user = User.create(user)

    if (@user.save)
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to root_path
    else
      render "edit"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = params[:user]
    @user = User.find(params[:id])
    @user.update_attributes({name: user['name'], email: user['email']})
    render :show
  end

  def change_roles
    @user = User.find(params[:id])
    @roles = UserRole.all
  end

  def update_roles
    message = ''
    roles_to_link = params[:roles_to_link]
    user = User.find(params[:id])
    roles_to_link.each do |r|
      role = UserRole.find(r[0])
      if (r[1] == '1')
        if (!user.user_roles.exists?(role))
          user.user_roles << role
          message += role.title.humanize + ' role was added to user ' + user.name
        end
      else
        if (user.user_roles.exists?(role))
          message += role.title.humanize + ' role was removed from user ' + user.name
          user.user_roles.delete(role)
        end
      end
    end

    redirect_to action: 'index', message: message
  end

  def destroy
    begin
      User.destroy(params[:id])
      render json: {message: 'User with id ' + params[:id] + 'has been deleted'}
    rescue Exception => e
      render json: {responseText: 'User could not be deleted due to ' + e.to_s, :status => 422}
    end
  end

  #helper methods

  def generate_dummy_password
    password_length = 8
    password = Devise.friendly_token.first(password_length)

    return password
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/change_roles.html.erb
<div class="edit-form">
  <%= form_for(@user, url: {action: :update_roles}, html: { method: :post}) do |f| %>
  <ul class="checkbox-list">
    <% @roles.each do |r| %>
        <li>
          <label>
            <%= check_box 'roles_to_link', r.id, {checked: @user.user_roles.include?(r)} %>
            <%= r.title %>
          </label>
        </li>
    <% end %>
  </ul>
  <div class="edit-row">
    <%= f.submit 'Save' %>
    <input id="cancel-edit" type="submit" value="Cancel"/>
  </div>
  <% end %>
</div>

app/views/user/edit.html.erb
<div class="edit-form">
  <div class="validation-errors">
    <%= @user.errors.full_messages.first if @user.errors.any? %>
  </div>
  <%= form_for @user, url: {action: :update} do |f| %>
      <div class="edit-row">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="edit-row">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="edit-row">
        <%= f.submit 'Update' %>
      </div>
  <% end %>
</div>

app/views/user/index.html.erb
<div class="page-content">
  <h3><i class="social foundicon-torso"></i> MAFT Users</h3>

  <div class="tile-list-cntr">
    <% if (@message != nil && @message != '') %>
        <div class="message-cntr"><%= @message %></div>
    <% end %>
    <h4>Your User Details</h4>
    <ul class="tile-list">
      <li class="tile-list-row">
        <h5><%= @current_user.name %></h5>

        <div class="form-row"><a href="mailto:<%= @current_user.email %>"><%= @current_user.email %></a></div>
        <% if (@current_user.user_roles.length > 0) %>
            <h5>User Roles</h5>
            <ul>
              <% @current_user.user_roles.each do |r| %>
                  <li>
                    <%= r.title.humanize %>
                  </li>
              <% end %>
            </ul>
        <% end %>
        <div class="tile-controls">

          <a href="#" data-dropdown="drop1" class="button dropdown tiny radius">Options</a><br>
          <ul id="drop1" class="f-dropdown">
            <li><%= link_to 'View Details', user_path(id: @current_user) %></li>
            <li><%= link_to 'Edit Details', edit_user_path(id: @current_user) %></li>
            <li><%= link_to 'Change Password', edit_user_registration_path %></li>
            <li><%= link_to 'Change Roles', user_change_role_path(id: @current_user) %></li>
          </ul>
        </div>
      </li>
    </ul>

    <h4>Other User Details</h4>

    <div><%= link_to raw('<i class="general foundicon-plus"></i> Add New User'), :new_user, class: 'button tiny radius' %></div>
    <% if (@users) %>
        <ul id="other-users" class="tile-list">
          <%- current_user.id %>
          <% @users.each do |u| %>
              <li class="tile-list-row">
                <h5><%= u.name %></h5>

                <div class="form-row"><a href="mailto:<%= u.email %>"><%= u.email %></a></div>
                <% if (u.user_roles.length > 0) %>
                    <h5>User Roles</h5>
                    <ul>
                      <% u.user_roles.each do |r| %>
                          <li>
                            <%= r.title.humanize %>
                          </li>
                      <% end %>
                    </ul>
                <% end %>
                <div class="tile-controls">
                  <a href="#" data-dropdown="drop<%= u.id %>" class="button dropdown tiny radius">Options</a><br>
                  <ul id="drop<%= u.id %>" class="f-dropdown">
                    <li><%= link_to 'View Details', user_path(id: u) %></li>

                    <li><%= link_to 'Edit Details', edit_user_path(id: u) %></li>
                    <li>
                      <% link_to 'Reset Password', user_path(id: u) %></li>
                    <li><%= link_to 'Change Roles', edit_user_password_path(id: u) %></li>
                    <li>
                      <a data-userid="<%= u.id %>" data-username="<%= u.name %>" href="javascript:void(0)" class="delete-user">Delete
                        User</a></li>
                  </ul>
                </div>
              </li>
          <% end %>
        </ul>
    <% end %>

  </div>
</div>

app/views/user/new.html.erb
<div class="edit-form">
  <div class="validation-errors">
    <%= @user.errors.full_messages.first if @user.errors.any? %>
  </div>
  <%= form_for @user, url: {action: :create} do |f| %>
      <div class="edit-row">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="edit-row">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="edit-row">
        <%= f.submit 'Create' %>
      </div>
  <% end %>
</div>

app/views/user/show.html.erb
<h4><%= @user.name %></h4>
<div>
  <%= link_to 'Return to Users Page', :users_index %>
  <%= link_to 'Edit Details', edit_user_path %>
  <div class="form-row"><label>Email: </label><span><%= @user.email %> </span></div>
</div>